### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by promindsd** [abassign/G91-R1B_HD#7]
Hello there!
I downloaded your excellent project and tried to use it with FlightGear 2018.3.2 but it fails to start.
I always get this message from FG and then it quits.

FGPropertyValue::GetValue() The property systems/gauges/PHI/attitude/gyrocompass-magnetic-deg-var-linear-360 does not exist.

**Comment by abassign** [comment]
I know the problem, as I had to insert a new module in JSBSim that was
officially included in the 2019.1 repository of FGFS. The module is the
necessary linear actuator that replaces several hundred lines of JSBSim
code with a few lines ... I therefore advise you to download version 2019.1
or better 2019.2: for Windows or MAC you can find it here:
http://download.flightgear.org/builds/nightly/  if you use Linux Debian
Like (as Ubuntu) is sufficient read this instruction:
http://wiki.flightgear.org/Scripted_Compilation_on_Linux_Debian/Ubuntu
I hope you like the plane, it is certainly now the most complicated and
complex plane of FGFS, but it also works with GPUs of 2GB of RAM and Intel
or AMD processors without external GPU of the latest generation (a bit 'on
the limit though. ..) like the i7 series.
Currently I have not done the article for the FGFS wiki so use the G91
flight manual .. consider that it is the same since all the systems
(electric, fuel, hydraulic, instrumentation, ADF, TACAN ...) are almost 1 :
1 with those of the real plane.
If you use it let me know if you have any problems as it is in the testing
phase, I will always answer you as far as possible.
Have fun :)
P.S:
Multiuser display doesn't work yet, I still have to work on it.

**Comment by promindsd** [comment]
Ok, fine. I did not realize this plane was developed for the 2019.1 release. I would certainly like to use your plane and I will try to download and compile the 2019 release of Flightgear.
Keep on doing the good work! :-)

**Comment by abassign** [comment]
I am very happy that everything is ok, I wanted to ask you about what kind
of PC (clock processor), GPU and operating system are you using and what
are the performances (fps) to understand if there is the possibility to
improve the system again.

Greetings

Adriano

**Comment by promindsd** [comment]
I use Linux/Fedora running on a I7 CPU@3.60GHz, 24GB RAM, Nvidia GTX 1050Ti.
With this setup I always get 30+fps @ 1920x1080. Depending on rendering load/scenario, I sometimes get 60fps.
